### ISSUE TITLE
Property “language” has inconsistencies when displayed in a query/search

### ISSUE THREAD

**Issue by ivonns** [NICMx/rdap-server#10]
The property “Language” is displayed in the tag of Entities and Nameservers when is made a query or search. However, language’s property doesn´t appear in the configuration’s files of entity or nameservers. Which means that the property could not be hidden. Therefore, it is suggested add a language’s property in the configuration’s files of entity and nameservers, with the purpose of hide this value when needed.

**Comment by Zakrom** [comment]
Attribute "lang" has been added to the provacy properties of the rdap main objects and also to remarks. It was considered unnecesary to assign a language to each and every object  so only the main five objects and remarks will keep this attribute.

The property language is now obtained from the configuration properties, this language is shared between rdap main objects. Remarks is going to keep it´s language as it can be custom made by  a user .
