### ISSUE TITLE
SLF4J in war File

### ISSUE THREAD

**Issue by mortensen** [NICMx/rdap-server#100]
I am trying to deploy the server war file into an embedded Jetty in my project. But everytime I am getting this eror:

java.lang.LinkageError: loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader (instance of org/eclipse/jetty/webapp/WebAppClassLoader) of the current class, org/slf4j/LoggerFactory, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature

Problem is, the war file aready contains slf4j. I tried to change my maven pom  to "<scope>provider</scope>, which didn't help. Any suggestions?

**Comment by dhfelix** [comment]
Hi, I was trying to figure it out how to run the RDAP-server with Jetty, but we don’t have enough experience running Servlets with Jetty and it's taking me some time to deploy the server. 

Maybe you could provide us your configuration if it's a test and non-production setup.

**Comment by mortensen** [comment]
Honestly we experienced a lot of problems with your project due to the fact that it is available only as WAR file and not as a jar file. I was able to start the project in tomcat and in jetty. In Jetty only, If I changed the web.xml and added the leading slash to the WEB-INF string. See here issue #101 . But that's not all changes. I later was able to fix the logging problem mentioned here by adding other log4j dependencies to the war file. But all of this only ran in Jetty and Tomcat, NOT in the embedded versions of both. Because there the start page was shown, but the service itself wasn` t called. Instead it hit an error page. In our case we also wanted to use spring for our DAO implementation. Which would mean adding another bunch of jars, all into  the WAR. And this is not practicable. Extracting the war, changing the web.xml, adding new libs, packing it again... It would be way better if all dependencies where available as jar files in a maven repository. So that you could use them in Spring Boot or similar ones.

**Comment by mortensen** [comment]
Due to the changes supporting maven and not having to use the packed war file this ticket can be closed.
