### ISSUE TITLE
Compatibility issue between Tomcat and Jetty

### ISSUE THREAD

**Issue by mortensen** [NICMx/rdap-server#101]
RdapInitializer needs a fix for userFilePath in case it's not configured. The path works in Tomcat, but not in Jetty. With a leading Slash it will work in both.

**Comment by mortensen** [comment]
Made a pull request for this.

**Comment by Ephenodrom** [comment]
Got the same problem on my site ... waiting for the fix now :)

**Comment by dhfelix** [comment]
Hi, sorry for the delay, I took a day off, and I was finishing some new features for RDAP-server.

Let me check the fix.

**Comment by dhfelix** [comment]
Hi, sorry for the delay, I took a day off, and I was finishing some new features for RDAP-server.

I'm going to check the fix, thanks.

**Comment by dhfelix** [comment]
RedDog is now published in maven repository https://search.maven.org/search?q=g:mx.nic.labs.reddog, the pull request was integrated in rdap-server 1.4.2 

groupId was changed in the process of the upload to maven

**Comment by dhfelix** [comment]
RedDog is now published in maven repository https://search.maven.org/search?q=g:mx.nic.labs.reddog, the pull request was integrated in rdap-server 1.4.2

The groupID was modified during the upload process to maven.

**Comment by mortensen** [comment]
Thats a great addition, thanks for this work. I will try to test it the next days, as soon as there is time. Will close the ticket then.
