### ISSUE TITLE
IDN Domain names where the Unicode contains letters not in the Latin character set

### ISSUE THREAD

**Issue by huwsteadCL** [NICMx/rdap-server#106]
We seem to have an issue rendering some IDN domains.

We are storing the domains in UTF8 within the domain.dom_unicode_name field.

If the IDN only contains characters with the latin character set (e.g. éxample) then the domain is rendered correctly in a domain query in the RedDog frontend.  Conversely if the IDN contains non-latin characters (e.g. Russian / Chinese / Arabic etc) then the RedDog frontend always returns a 404 Object not found error.

Not sure if this is some mis-configuration on our end or a genuine bug in the current implementation

**Comment by dhfelix** [comment]
I don't have that issue, my local server can display japanese and arabic characters.
If you are using mysql, try adding the following queryparam to your connection.
`characterEncoding=UTF-8`
e.g.
```
jdbc:mysql://localhost:3306/rdap?useSSL=false&characterEncoding=UTF-8
```

**Comment by huwsteadCL** [comment]
Thanks for that..  we did indeed not have the UTF-8 param set on our connection :(
