### ISSUE TITLE
Database schema changelog - v1.4.1 to v1.4.2

### ISSUE THREAD

**Issue by huwsteadCL** [NICMx/rdap-server#108]
Hi

With the release of RDAP-SQL-provider v1.4.2 I wanted to check if there are any DB schema changes that need to be applied?

Looking at https://www.reddog.mx/database-changelog.html#database-schema-changelog I don't see any entries but not sure if this is just an outdated page or if there aren't any actual schema changes.

If you could clarify it would be appreciated

**Comment by dhfelix** [comment]
Hi, 

Only Java source code was modified.
No changes to SQL or schema were made.

**Comment by huwsteadCL** [comment]
Perfect.  Thanks for the very rapid response
