### ISSUE TITLE
In DB language’s value is stored in table Remarks, but it doesn’t appear in Entity or Nameserver.

### ISSUE THREAD

**Issue by ivonns** [NICMx/rdap-server#11]
Language’s value it’s not stored in the table of Entities or Nameservers; however, when doing a query/search this value is shown in that sections. Therefore, it is suggested to review if the language’s value should be stored in Entity or Nameservers’s tables.

**Comment by DAlpuche** [comment]
For theirs nature, it's unnecessary add a language attribute in the database for the Entity or Nameservers.  
On the other hand, the remarks,in a future enhancement, may be retrieved from the database depending on the language defined in the server.
