### ISSUE TITLE
Query/search not display information of domains in zone which is not mx.

### ISSUE THREAD

**Issue by ivonns** [NICMx/rdap-server#12]
It has been made a search/query for a domain which not belongs to mx’s zone, as a result is displayed a 404 error code. The zone was properly set in configuration.properties’ file. 
Steps to reproduce:
    1)	Set several zones in configuration.properties’ file.
    2)	Make a search/query of a domain with a different zone than mx

**Comment by dhfelix** [comment]
The user was modifying the default configuration in "src / META-INF", and the user had a different configuration in the "WEB-INF" folder where the "zone" attribute only had the value "mx", and the expected behavior is that the Properties that are in WEB-INF override the META-INF configuration.
