### ISSUE TITLE
Domains can have more than one registrar at a time.

### ISSUE THREAD

**Issue by OblivionWielder** [NICMx/rdap-server#13]
When defining relationship between entities and roles for a domain, There is the possibility that a domain can have several REGISTRARS binded with a domain at any given time. This type of relationship, in the context of the server, defines a type of ownership over the domain.
Nonetheless, such type of relation can't be more than one at any given time. 

Expected behavior:
Only one registrar at any given time, having ownership of the domain. Past relationships with registrars should be with related with events.
Actual behavior:
Multiple relationships between a domain and a registrar entity are possible

**Comment by DAlpuche** [comment]
In the RTY-RAR model isn't allowed a situation where same role is used with multiple entities in a Domain, therefore to avoid this situation we added an unique index in the domain_entity_roles table containing the columns (dom_id,rol_id).
Greetings
