### ISSUE TITLE
Does not work on *nix

### ISSUE THREAD

**Issue by ydahhrk** [NICMx/rdap-server#15]
The code is using backslashes in file names. This is the Windows way; it doesn't work anywhere else.

For the record, I found this issue in `JsonUtil#createTermsOfService(String)` and `HelpResult#HelpResult(ServletContext)`. This is not intended to be an exhaustive list.

**Comment by Zakrom** [comment]
It should be fixed now, these methods now use  Paths instead of a String directly, I´d like to mention that I am still looking for any other occurences of this problem anywhere else.

**Comment by ydahhrk** [comment]
I seems to be working fine.
