### ISSUE TITLE
Reverse resolution is not working properly.

### ISSUE THREAD

**Issue by ivonns** [NICMx/rdap-server#18]
When doing a query asking for a domain in reverse resolution it shown a message error indicating that the zone it´s not found. However, the zone is set as managed in the configuration.properties.
Apparently, there is a problem when asking for something that seems to be an IP, because the error about zone not found continues appearing. Nevertheless, when doing a query with something similar like a domain name and the zone of in-addr.arpa or ip6.arpa the response said in fact that the object is not found, but there is no problem with the zone in this case.
_Asking for reverse resolution_
/rdap-server/domain/0.1.168.192.in-addr.arpa
Response:
{"rdapConformance":["rdap_level_0"],"errorCode":"404","title":"Object not found","description":"Zone not found."}

_Asking for a domain in the zone in-addr.arpa_
/rdap-server/domain/0.in-addr.arpa
Response:
{"rdapConformance":["rdap_level_0"],"errorCode":"404","title":"Object not found","description":"Object not found."}

**Comment by Zakrom** [comment]
Reverse addresses specifically were not being validated by the implementation so they were being discarded.
Now both the implementation and the servlet are validating this.
