### ISSUE TITLE
Internal server error when consulting a domain without a zone.

### ISSUE THREAD

**Issue by ivonns** [NICMx/rdap-server#20]
When doing a query asking for a domain without a zone, the application shows an error 500. It is suggested that in this case could be shown an error 400 for malformed query or 404 for object/zone not found. 

This is an example of the query that produces the error:
http://localhost:8080/rdap-server/domain/dn19

**Comment by Zakrom** [comment]
When validating the zone in the request it wasn´t checking if there is a zone at all, so  a validation for this  was added just before the zone validation.
