### ISSUE TITLE
Does not allow multiple implementations of the data access API in the classpath.

### ISSUE THREAD

**Issue by ydahhrk** [NICMx/rdap-server#22]
This is not that diffucult to work around, but it makes the installation process somewhat awkward.

If the RDAP server finds multiple implementations of the data access API, it crashes and refuses to start. This means that, in order to install a new data access implementation, the old one has to be explicitly removed.

One problem with this is that it forces the user to fake-deploy before the data access implementation can be replaced. The default implementation ships with the server WAR, so to switch the implementation I need to

1. Start the servlet container (expand the WAR).
2. Remove the old implementation from the classpath.
3. Copy the new implementation in.
4. Restart the servlet container to apply changes.

Starting the servlet container before the app is configured is unnatural. This should be less traumatic:

1. Copy the new implementation in.
2. Tell Red Dog which implementation should be used via configuration.
3. Start the server.

Another drawback is that forcing one implementation per classpath forces the user to keep track of which implementations have been installed in the past. This would not be the case if only the valid one has to be referred to in a file.

**Comment by jcanomx** [comment]
How about this, if the RDAP Server finds 2 implementations of the data access API, the default implementation and a new one, the Server will automatically give preference to the later one. This way, you don’t have to remove the default implementation of the classpath or configure anything.

Now the question here is what happens if the Server finds 3 or more implementations? Should the Server throw the exception and shut itself down?

**Comment by ydahhrk** [comment]
> How about this, if the RDAP Server finds 2 implementations of the data access API, the default implementation and a new one, the Server will automatically give preference to the later one.

Fair enough.

> what happens if the Server finds 3 or more implementations?

Why not use the file?

I think of your idea as a reasonable fallback strategy in case some ambiguity can be worked around, but I don't see how preventing the user from keeping many implementations in the classpath (with a simple swap switch) helps anyone.

**Comment by jcanomx** [comment]
All right then, let’s keep the fallback strategy, and use a configuration parameter to allow the user to select from multiple implementations. I’m still think is a little odd that someone might need multiple custom implementations in the classpath, but then again this solution is easy to implement and gives the user more options.

**Comment by ydahhrk** [comment]
> How about this, if the RDAP Server finds 2 implementations of the data access API, the default implementation and a new one, the Server will automatically give preference to the later one. This way, you don’t have to remove the default implementation of the classpath or configure anything.

Just to clarify: The default implementation depends on the data access API (which is where the implementation loader sits right now), not the other way around, so the implementation loader is incapable of recognizing the default implementation among several candidates. After an off-thread discussion, we decided not to implement this feature.
