### ISSUE TITLE
'zones' configuration value is a trap

### ISSUE THREAD

**Issue by ydahhrk** [NICMx/rdap-server#28]
https://www.reddog.mx/behavior-configuration.html#zones:

> Zones managed by the server. The server will only serve domains that match this zone.

I find this field odd. Shouldn't the data access implementation be the one deciding this?

The field is especially jarring because it doesn't ship with a default value, so domain querying just plain doesn't work by default.

I feel that things should work by default. If the user doesn't want certain zones to be served, they will naturally lock them in the data access implementation. On the other hand, as it is, this field will be a natural trap for new users (who are just testing Red Dog) to fall straight into.

I think that this field should be purged. Either that or default to "manage everything".

**Comment by pcarana** [comment]
The zones are now configured at the implementation. The default value is a wildcard "*" that means "all zones".

This configuration has been removed from the server.

**Comment by TheRedTrainer** [comment]
Verified. The default configuration for zones management is to allow all the zones configured in database.
