### ISSUE TITLE
The `is_reverse_ipv#_enabled` options don't really belong to the server's configuration

### ISSUE THREAD

**Issue by ydahhrk** [NICMx/rdap-server#29]
The reason why `is_reverse_ipv4_enabled` and `is_reverse_ipv6_enabled` exist is because these searches can be expensive.

But that's only assuming the SQL provider is being used with default queries. I don't think it's sensible for the server to be making assumptions regarding the data access implementation's performance.

These keys belong to the SQL provider.

**Comment by pcarana** [comment]
Agree, this has been moved to the provider.

**Comment by TheRedTrainer** [comment]
Verified. The is_reverse_ipv4_enabled and is_reverse_ipv6_enabled properties were moved to data-access.properties file.
