### ISSUE TITLE
Incorrect query skips zone id's 

### ISSUE THREAD

**Issue by OblivionWielder** [NICMx/rdap-server#3]
When doing a search for a domain other than .MX, the query will bring zero results. This is due to an issue in which the "IN" part of the query fails to correctly include all the options for the possible zone_id's 
Problem appears to be that instead of being ('80, 83'), listing should be in the ('80', '83') format.

Setup:
Answering for .mx and .lat zones
Domains---
foo223947726.lat
mydomain.mx
TLD's---
.mx = 80
.lat = 83
Queries performed--
SELECT d.* FROM rdap.domain d WHERE d.dom_ldh_name = 'foo223947726' AND d.zone_id IN ('80, 83') ORDER BY 1 LIMIT 5;
SELECT d.* FROM rdap.domain d WHERE d.dom_ldh_name = 'mydomain' AND d.zone_id IN ('80, 83') ORDER BY 1 LIMIT 5; 

Steps:
1. Go to rdap domain search url
2. Put mydomain.mx as the ldh name
3. See result
4. Change ldh name for lat one
5. See results

Expected:
See the information regarding the .lat domain 

Actual result:
404 Error

**Comment by Zakrom** [comment]
When looking for a partial zone query it was quoting because of an string insertion in a parameter.
Now the query is dynamic adding the needed parameters then setting from
a list to the statement.
