### ISSUE TITLE
Default value of `owner_roles` doesn't make sense to me

### ISSUE THREAD

**Issue by ydahhrk** [NICMx/rdap-server#31]
Quoting [RDAP Operational Profile for gTLD Registries and Registrars](https://www.icann.org/resources/pages/rdap-operational-profile-2016-07-26-en#III):

> 1.5.8. The domain object in the RDAP response MUST contain entities with the following roles. Exactly one entity per role MUST be present in the response, each of them with a handle (ROID of the contact object, <contact:roid>, as defined in RFC5733) and valid members fn, adr, tel, email (as specified in RFC6350, the vCard Format Specification and its corresponding JSON mapping RFC7095):
> 
> - registrant
> - administrative
> - technical

Given that's listed among the requirements that need to be followed by **both** registries **and** registrants (and presumably also others), is there any reason why the default value of `owner_roles` should **not** be "administrative"?

**Comment by pcarana** [comment]
I agree, there should be a default value distinct than **empty** . Analizing the issue we've realized that the `owner_roles` property is applied on all objects, and this isn't entirely correct.

Let's take an example to clarify this. In the case of a **domain** object the owner should be the **registrant** entity, but in the case of a **nameserver** object the owner should be the **registrar** entity (at least for a registry that handles nameservers as objects); and apparently for an **ip** object the owner could be the **administrative** entity.

So, the `owner_roles` should be configured by objects and each property could have its default value, eg:
`domain.owner_roles = registrant`
`nameserver.owner_roles = registrar`

We're still analizing this to solve the issue.

**Comment by pcarana** [comment]
Discussing the issue with the team, we've decided to implement the solution where each object (except entities) will have its own owner roles configured and with a default value. Here are the default values for each object:

- **ip** = administrative
- **autnum** = administrative
- **domain** = registrant
- **nameserver** = registrar

Commit of the solution in the next minutes...

**Comment by TheRedTrainer** [comment]
Verified. The configuration.properties file now include the following owner roles properties (with the corresponding default value):

owner_roles_ip                 =  administrative
owner_roles_autnum        =  administrative
owner_roles_domain        =  registrant
owner_roles_nameserver =  registrar
