### ISSUE TITLE
Internal server error when accesing "/exception" servlet

### ISSUE THREAD

**Issue by pcarana** [NICMx/rdap-server#33]
Currently the server has a servlet to handle errors, this servlet is bounded to the location "/exception". This location may be used internally, but still it can be accessed externally; so when somebody access "rdap-server/exception" the server throws a NullPointerException and responds a 500 error.

I would like to make a suggestion: why not use a filter instead of a servlet? The servlet works fine, but it can give this kind of problems. Also, just in case that you decide to stay with the servlet, I suggest this: when the servlet is directly accessed it should respond with a 404 code, since that service is not part of the RDAP specs.

**Comment by pcarana** [comment]
If the servlet is directly accesed it will respond a **404** error code, since this service shouldn't exist.

**Comment by TheRedTrainer** [comment]
Verified. If an user send a request to rdap server like 

> http://localhost:8080/rdap-server/exception

the server returns the following answer

> {"rdapConformance":["rdap_level_0"],"notices":[{"title":"TOS","description":["TOS"],"type":"TOS","links":[{"value":"TOS","href":"example.com/TOS"}]}], "errorCode":"404","title":"Object not found","description":"/rdap-server/exception"}
