### ISSUE TITLE
Internal server errors are logged as warnings

### ISSUE THREAD

**Issue by pcarana** [NICMx/rdap-server#34]
The servlet "ExceptionServlet" creates an instance of "ExceptionResult" whenever its called. One of the cases in the constructor of "ExceptionResult" expects the code 500 (Internal server error); when this code is reached the error is handled as any of the others, but I believe that it should be handled in a different way.

The response for the request is ok, since the client only needs to know that an error has occurred; but internally the server should show more information about the error for the administrators to take the necessary actions on this error. It could show the stacktrace or somethig more informative than "WARNING: 500: ".

**Comment by pcarana** [comment]
This kind of errors/exceptions are now logged as SEVERE and also a stacktrace is logged at the server.

**Comment by TheRedTrainer** [comment]
Verified. If a 500 error-code exception happens, the exception is logged as SEVERE (for example, a context.xml configuration that doesn't allow to connect to DB)

09-Oct-2017 18:09:45.469 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class mx.nic.rdap.server.listener.RdapInitializer
 java.lang.IllegalArgumentException: mx.nic.rdap.db.exception.InitializationException: Trouble loading country codes from the DB.
