### ISSUE TITLE
Reestructure the package mx.nic.rdap.server

### ISSUE THREAD

**Issue by pcarana** [NICMx/rdap-server#36]
This is only a suggestion so that the code organization can be improved. Currently the package **`mx.nic.rdap.server`** has many classes of many types; this classes can be moved to other packages so that they will be placed on a more appropiated package. The reestructuration that I propose is this:

- **_AcceptHeaderFieldParser_**: is used by **RdapServlet**, further in this list is a proposal for relocate **RdapServlet**, so **AcceptHeaderFieldParser** could be relocated to the same package or to a new package **`mx.nic.rdap.server.servlet.xxx`**.
- **_DataAccessServlet_**: could be placed at **`mx.nic.rdap.server.servlet`**.
- **_RdapConfiguration_**: could have its own package, something like **`mx.nic.rdap.server.configuration`**.
- **_RdapInitializer_**: is a **WebListener**, so it could have its own package **`mx.nic.rdap.server.listener`**. This new package could be useful for somebody that could want to add its own listeners.
- **_RdapResult_**: could be placed at **`mx.nic.rdap.server.result`**.
- **_RdapSearchRequest_**: is used exclusevely used by the servlets, so it can be placed at that package **`mx.nic.rdap.server.servlet`** or to a new sub-package **`mx.nic.rdap.server.servlet.request`**.
- **_RdapServlet_**: could be placed at **`mx.nic.rdap.server.servlet`**.
- **_Renderer_**: could be placed at **`mx.nic.rdap.server.renderer`**.
- **_RendererPool_**: could be placed at **`mx.nic.rdap.server.renderer`**.
- **_UserInfo_**: is only referenced by the classes at **`mx.nic.rdap.server.result`** so it could be placed at that same package.
- **_NoticesHandler_**, **_NoticesReader_** and **_UserNotices_**: the 3 classes handle XML and objects **Notices**, the proposal is to place them in a new package called **`mx.nic.rdap.server.notices`** or **`mx.nic.rdap.server.xml`** (honestly I prefer the first option).

**Comment by pcarana** [comment]
The classes where reestructured as proposed.

**Comment by TheRedTrainer** [comment]
Verified. All the classes were organized in the corresponding packages.
