### ISSUE TITLE
ExceptionResult only expects 6 error codes

### ISSUE THREAD

**Issue by pcarana** [NICMx/rdap-server#38]
The object only expects 6 error codes inside its constructor, so what happens when a different code arrives as part of the parameter? For instance, when the server returns a 429 code. In this case there's no title nor description for the error.

Maybe there aren't many error codes currently returned by the server, but the "inconsistency" will grow if someone wishes to add more codes (eg. 301, 302, 303, 40x, etc.) on its own implementation. Probably the best solution will be to place a default case for the switch statement.

Beside this, I would like to suggest another thing. The codes are harcoded, wouldn't be better to declare them as constants or use something that already exists (eg. **javax.servlet.http.HttpServletResponse.SC_\***)?

**Comment by pcarana** [comment]
> Probably the best solution will be to place a default case for the switch statement.

The default case in the switch statement was added on commit 33d155222b40e84fc07079b6768faf79740faea1, so if there are any other codes to add they can be added at this statement; for now this will return a default message.


> Beside this, I would like to suggest another thing. The codes are harcoded, wouldn't be better to declare them as constants or use something that already exists (eg. javax.servlet.http.HttpServletResponse.SC_*)?

Most of the codes expected by the servlet are declared as constants in the mentioned class (`javax.servlet.http.HttpServletResponse`), but the code 422 isn't, so that's why the codes stayed the same (as Strings).

**Comment by TheRedTrainer** [comment]
Verified. If a non listed error code is returned by a client request, the following structure is displayed in the answer: 
{"rdapConformance":["rdap_level_0"],"errorCode":"501","description":"This server does not implement ip requests."}

**Comment by pcarana** [comment]
Closing, fixed in Red Dog v1.2
