### ISSUE TITLE
Operational profile remark is overwritten when rendering JSON

### ISSUE THREAD

**Issue by pcarana** [NICMx/rdap-server#39]
This issue can be reproduced when the server uses a profile distinct than "none". The class `JsonRenderer` tries to add the operational profile remark (line **60-61**), and I say "tries" because after that intent the remarks are overwritten by the remarks that the result already had (line **63-64**).

Precisely in the same scenario where the server has a profile, other remarks are placed before rendering the object, exactly at `DomainResult` and `DomainSearchResult` method _`validateResponse()`_. Or even this could happen if another remark is added in another flow (eg. entity search).

Probably the quickest solution is: if the remark is to be added at this level (`JsonRenderer`), it should be added to the list of existent remarks so that it doesn't get lost when rendering the object. The function currently used [`javax.json.JsonObjectBuilder.add(String name, JsonValue value)`](http://docs.oracle.com/javaee/7/api/javax/json/JsonObjectBuilder.html#add-java.lang.String-javax.json.JsonValue-) doesn't help much right now since "If the object contains a mapping for the specified name, this method replaces the old value with the specified value". This solution could imply to modify the object received as parameter, or to add some validation at the cycle of lines **63-65**, which personally I wouldn't consider the "cleanest" option.

My proposal is that this remark should be added at another level, so that the renderer do what's supposed to do: to render and not to alter the object.

**Comment by pcarana** [comment]
The implementation was confusing since the server didn't implemented much of what the Operational Profile states, so it has been removed, it had too much work still to be done (code and documentation) and also could create false expectactions.

The "terms of service" were loaded depending on the operational profile, now they are loaded if the file exists.

**Comment by TheRedTrainer** [comment]
Verified. The operational profile functionality was removed from rdap server. The terms of service are loaded if tos.xml default file is configured.
