### ISSUE TITLE
 Domain name should not have the ccTLD concatenated

### ISSUE THREAD

**Issue by ivonns** [NICMx/rdap-server#4]
**Description**
When inserting a domain using the insertDomainAndGet’s method located in DomainTest.java, the domain has the ccTLD concatenated. The domain name should not have contactenated the ccTLD, it should be just the name of the domain. 
(Hint: this could be found un line 136)

**Comment by DAlpuche** [comment]
Changed the value assigned to the domain name, without the ccTLD.
