### ISSUE TITLE
Remarks values are harcoded and loaded in a validation function

### ISSUE THREAD

**Issue by pcarana** [NICMx/rdap-server#40]
The remarks that are used whenever the profile is distinct than "NONE" are harcoded in `mx.nic.rdap.server.util.Util`, I think that could be better to have them in a file just like the notices.

My proposal is to place this remarks (_EppInformationRemark, WhoisInaccuracyComplaintFormRemark, and OperationalProfileRemark_) in a file similar to `notices.xml`, maybe `remarks.xml` but with an additional option to indicate on which profile the remark is going to be used. This implies to create it's own schema just to differentiate them from the notices.

Beside this, currently two of the remarks (_EppInformationRemark and WhoisInaccuracyComplaintFormRemark_) are being loaded at the function `validateResponse()` in `DomainResult` and `DomainSearchResult`. Just as its name indicates, the function should be used to validate, so I suggest that this remarks will be loaded in another function, something like `loadRemarks()`; of course this will depends somehow of the first proposal in this issue and also could be affected by the solution (if it's going to be solutioned) of the issue #39.

**Comment by pcarana** [comment]
The implementation was confusing since the server didn't implemented much of what the Operational Profile states, so it has been removed, it had too much work still to be done (code and documentation) and also could create false expectactions.

The "terms of service" were loaded depending on the operational profile, now they are loaded if the file exists.

**Comment by TheRedTrainer** [comment]
Verified. The operational profile functionality was removed from rdap server. The terms of service are loaded if tos.xml default file is configured.
