### ISSUE TITLE
Zone validation is case sensitive in domain search

### ISSUE THREAD

**Issue by pcarana** [NICMx/rdap-server#42]
Assuming that the server has configured the zone "bar" at `configuration.properties`, it will only allow the search of domains of such zone (nothing new). The issue appears when the zone of the searched domain isn't literally "bar". This is easier to explain with an example, if the following search is made:
_/domain/foo.bar_
assuming that "foo.bar" exists in my database, the response code will be 200 (OK). But if the search is:
_/domain/foo.BAR_
the response will be 404 (Not found), and in the body will contain the text "The zone is unmanaged by this server.".

The zones are loaded in the application just as they are written in the configuration file (`mx.nic.rdap.server.RdapConfiguration.validateConfiguredZones()`), so whenever they are validated (`isValidZone(String)` or even at `isValidReverseAddress(String)`) the validation will succeed if it's an exact match. I would suggest that the zone can be case insensitive.

**Comment by pcarana** [comment]
The configured zones are now case insensitive.

**Comment by TheRedTrainer** [comment]
Verified. If you search the example.org domain as "domain/example.ORG" or "domain/example.org", the search brings the same results because now the validation is case insensitive.
