### ISSUE TITLE
IllegalArgumentException when using an invalid PrivacyStatus value

### ISSUE THREAD

**Issue by pcarana** [NICMx/rdap-server#44]
Whenever an invalid value is placed at the properties in `webapp/WEB-INF/privacy/*.properties` an `IllegalArgumentException ` is thrown. Eg. at the file "autnum_events.properties", set "eventAction=anyy" (note the typo) and start the server.

The issue is at `mx.nic.rdap.server.util.PrivacyUtil` function `loadObjectPrivacySettings(String)`. This block is at the function, I added some comments:
```java
String property = properties.getProperty((String) key).trim();
/** Here's the problem, the exception is never handled. The enum will never have an invalid value. **/
PrivacyStatus privacyProperty = PrivacyStatus.valueOf(property.toUpperCase());

switch (privacyProperty) {
case OWNER:
	break;
case AUTHENTICATED:
	break;
case ANY:
	break;
case NONE:
	break;
default:
	/** Good intentions, but the code is never reached **/
	isInvalidProperties = true;
	builder.append(key + "=" + property + ", ");
	continue;
}
```

**Comment by pcarana** [comment]
Whenever an invalid value is configured, the server will indicate it in a friendly manner (logged at console) since the exception `IllegalArgumentException` is now handled.

**Comment by TheRedTrainer** [comment]
Verified. If an invalid value is configured for privacy status properties (for example "supernintendochalmers" for handle property in domain.properties), the following stack trace is displayed on logs:

04-Oct-2017 19:05:44.200 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class mx.nic.rdap.server.listener.RdapInitializer
 java.lang.IllegalArgumentException: java.lang.RuntimeException: Invalid privacy file 'domain.properties'.
 Invalid values: handle=supernintendochalmers,
        at mx.nic.rdap.server.listener.RdapInitializer.contextInitialized(RdapInitializer.java:67)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4853)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5314)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:753)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:729)
