### ISSUE TITLE
Differences at "configuration.properties" default file (META-INF) and configurable file (WEB-INF)

### ISSUE THREAD

**Issue by pcarana** [NICMx/rdap-server#45]
Not critical but still important to mantain consistency between the files:

- Comments on properties **"zones"**, **"owner_roles"**, **"is_reverse_ipv4_enabled"**, **"is_reverse_ipv6_enabled"** and **"anonymous_username"** in file at `WEB-INF` indicate the default value but in file at `META-INF` don't indicate the default value.
- Additional comment _"Optional. Profile used to operate the server,{...}"_ on property **"operational_profile"** in file at `META-INF` isn't at the file in `WEB-INF`.
- Property **"allow_search_wildcards_anywhere"** (and its comment) is only present in file at `META-INF`, it isn't at file in `WEB-INF`.

**Comment by pcarana** [comment]
The files were synchronized.

**Comment by TheRedTrainer** [comment]
Verified. 
- Default values are included in META-INF file comments
- operational_profile was removed from both properties file due another issue fix
- "allow_search_wildcards_anywhere" property was included at WEB-INF/configuration.properties
