### ISSUE TITLE
Requests to "//domain/{existent.domain}" give a 404 code when it should be a 200 code

### ISSUE THREAD

**Issue by pcarana** [NICMx/rdap-server#46]
I hope to be clear explaining this issue, if not I'm open to receive comments. Assuming that my server context is "/" and that the domain "foo.bar" exists, a request to **"/domain/foo.bar"** should respond with a 200 code and its correspondent body; so far nothing new. If I make a request **"//domain/foo.bar"** or **"////domain/foo.bar"** I would expect the same result, a 200 code with the correspondent body.

What's actually happening is that I get a 400 code with the description "The requested domain does not seem to include a zone.". Just to add context, the [RFC 3986 URI Generic Syntax](https://tools.ietf.org/html/rfc3986#section-1.1.1) will help us. What's understood from there is that any number of "/" after the context is valid and so it should be resolved by the server; as I understood, it should be resolved as the context. Eg. "////" should be treated like "/".

So, the error code responded by the server is because the `DomainServlet` is reached but is getting as a parameter the same name of the service mapped to the servlet ("domain"); in another words, is searching the domain name "domain" instead of search "foo.bar". The root of the issue seems to be at `mx.nic.rdap.server.util.Util` function `getRequestParams(HttpServletRequest)`, since there is where the parameter is returned so that `DomainServlet` can use that parameter to make the search.

**Comment by pcarana** [comment]
The logic used to load the parameters from the URI has changed to load them correctly. Insted of parsing the URI, they are obtained using the Request Object that the servlet has. In another words, this task was already made by the servlet and the server wasn't using it.

**Comment by TheRedTrainer** [comment]
Verified. If an user makes a request for a domain info like 

http://localhost:8080/rdap-server///////////////domain/example.org

the result is the same as

http://localhost:8080/rdap-server/domain/example.org
