### ISSUE TITLE
Response code 501 on domain searches by name when zone isn't configured

### ISSUE THREAD

**Issue by pcarana** [NICMx/rdap-server#48]
This issue seems to be partially analized and fixed; right at ` mx.nic.rdap.server.servlet.DomainSearchServlet.getPartialSearch(String, RdapSearchRequest, DomainDAO)` there's this block:

```java
switch (request.getParameterName()) {
	case DOMAIN_NAME:
		if (!RdapConfiguration.hasZoneConfigured()) {
			// Is valid if there are no available zones, because the
			// rdap could only respond to autnum and ip networks
			// (RIR).
			throw new NotImplementedException();
		}
```

Fine, probably that's the case why the zones weren't configured, but what if they where intentionally not configured by other reasons, or they weren't configured just by mistake?

As I've understood, the server will return the 501 code when the configurator/user explicitly wants to, not by business validations (probably in some cases this is the best option). So, if the server _"could only respond to autnum and ip networks"_ the most likely case is that the other servlets (domain(s), nameserver(s)) will be disabled at a higher level.

My proposal is that instead of returning **"NotImplementedException"** the function could return a **"NotFoundException"** (if possible, with a significative message), since the service actually could be implemented.

The same issue is at function _getRegexSearch_ in the same class.

**Comment by pcarana** [comment]
Well, the fix was made but it has been invalidated by commit ec56939d622bd8252936d3a4a32b20af13283382 since the zones configuration has changed its logic and now depends mostly of the implementation.

**Comment by TheRedTrainer** [comment]
Verified. If a user searches a domain that is managed by a zone that is not configured in rdap-server (for example, domain.fr), the following error message is returned:

{"rdapConformance":["rdap_level_0"],"errorCode":"404","title":"Object not found","description":"Zone not found."}
