### ISSUE TITLE
Lookup paths aren't strictly used as Resource Identifiers

### ISSUE THREAD

**Issue by pcarana** [NICMx/rdap-server#49]
This a concept issue, specifically a REST concept issue. Keeping it simple, the theory is that a resource identifier can be a URL or a URN, and that "_REST uses a resource identifier to identify the particular resource involved in an interaction between components_" ([view more](https://www.ics.uci.edu/~fielding/pubs/webarch_icse2000.pdf)); so, for this case, the URL "http://rdap.example.com/domain/foo.bar" is not the same that "http://rdap.example.com/domain/foo.bar/hello".

When both examples are resolved in the server and assuming that domain foo.bar actually exists, both will respond the same: 200 response code and the domain information. Well, this is the issue.

Currently the logic implemented is first find the servlet (eg. /domain -> DomainServlet), then get the additional path values (eg. /foo.bar/hello) to use them as parameters in the correspondent servlet. So, if there are extra parameters they are ignored (eg. DomainServlet will only use the first parameter, for the example this is "foo.bar"). Exactly at this point is where the "Resource identifier" concept is broken.

The proposal is to use the URL as it should be used, as a resource identifier, so in case that an invalid/unknown identifier is received the correspondent response will be sent (could be a response code 404, 501, 400, ...).

This souldn't affect the behavior mentioned at [RFC 7480 - section 4.3](https://tools.ietf.org/html/rfc7480#section-4.3).

**Comment by pcarana** [comment]
An internal validation was added to the servlets, so that each servlet can indicate how many parameters they expect (parameters that are part of the URI, **NOT** of a query).

Almost every servlet expects 1 parameter (_/domain_, _/entity_, _/nameserver_, _/autnum_), only 1 servlet (_/ip_) expects maximum 2 parameters. The servlets related to searches (_/domains_, _/entities_, _/nameservers_) aren't affected by this behavior since it's logic is distinct.

**Comment by TheRedTrainer** [comment]
Verified. When an user searches a domain, entity, nameserver, autnum or ip using an extra parameter, the server returns an error message like this: 

http://localhost:8080/rdap-server/ip/192.168.1.2/32/patatas
> {"rdapConformance":["rdap_level_0"],"errorCode":"404","title":"Object not found","description":"/rdap-server/ip/192.168.1.2/32/patatas"}

http://localhost:8080/rdap-server/domain/d%C3%B3main44.org/test
> {"rdapConformance":["rdap_level_0"],"errorCode":"404","title":"Object not found","description":"/rdap-server/domain/d%C3%B3main44.org/test"}

**Comment by TheRedTrainer** [comment]
Verified. When an user searches a domain, entity, nameserver, autnum or ip using an extra parameter, the server returns an error message like this:

http://localhost:8080/rdap-server/ip/192.168.1.2/32/test
> {"rdapConformance":["rdap_level_0"],"errorCode":"404","title":"Object not found","description":"/rdap-server/ip/192.168.1.2/32/test"}

http://localhost:8080/rdap-server/domain/d%C3%B3main44.org/test
> {"rdapConformance":["rdap_level_0"],"errorCode":"404","title":"Object not found","description":"/rdap-server/domain/d%C3%B3main44.org/test"}
