### ISSUE TITLE
"Text" renderer should be associated with text/plain content-type

### ISSUE THREAD

**Issue by carlosm3011** [NICMx/rdap-server#50]
When using the "text" renderer the content-type is supposed to be set to text/html.

However, the result is plain text. The rendering behaviour of user tools is probably undefined.

One could:
- wrap the text in pre tags in order to have well-formed html
or
- use the text/plain content-type

**Comment by pcarana** [comment]
Hi there! We've been working on this. The renderized has been uncoupled from the server, to avoid this kind of issues (among other things). Now the server expects an implementation from [NICMx/rdap-renderer-api](https://github.com/NICMx/rdap-renderer-api) to render the results in the response.

The implementation can be configured at the server (eg. the server uses a default JSON Renderer at [WEB-INF/renderers.properties](https://github.com/NICMx/rdap-server/blob/devl-it07/src/main/webapp/WEB-INF/renderers.properties)). Just as seen in the `renderers.properties` file, the content-type of the renderer can be configured as a mime-type.

For the case of the text renderer, a reference implementation has been created (thanks to @dhfelix for this) and can be used at the server (currently at development phase in [branch devl-it07](https://github.com/NICMx/rdap-server/tree/devl-it07)); the so mentioned text implementation is at [NICMx/rdap-text-renderer](https://github.com/NICMx/rdap-text-renderer).

**Comment by pcarana** [comment]
Thanks @carlosm3011, the issue will be closed since this has been released in Red Dog v1.2 (don't forget to visit [Red Dog's homepage](https://www.reddog.mx)).
