### ISSUE TITLE
Configure IDN variant TLDs as Zones

### ISSUE THREAD

**Issue by TheRedTrainer** [NICMx/rdap-server#54]
Should rdap-server allow to configure an IDN variant TLD as a zone? 

I think that it would be useful to allow to configure any kind of TLD as a zone. The current configuration.properties and db table (rdap.zone) allow to configure only one name/representation per zone (for example .com, .lat, .mx). 

If you want to configure a TLD that includes a unicode char (for example eú) as a zone in db and configuration.properties, the server allows to configure only the u-label (eú) and query a domain including that unicode char, but there is no column in db or any property to configure the corresponding ldh name.

**Comment by pcarana** [comment]
Agree, this should be supported by the server. It's the reference implementation that doesn't support this, so this issue will be moved there and closed here (probably the core will be affected as well).
