### ISSUE TITLE
nsLdhName domain search returns 400 error code if uppercase value is sent

### ISSUE THREAD

**Issue by TheRedTrainer** [NICMx/rdap-server#56]
If an user executes a domain search by nsLdhName using a value that includes an uppercase letter (for example)

example.com/rdap-server/domains?nsLdhName=NS0.*.*

the server returns the following error:

**..."errorCode: 400, description: Only LDH domain labels are allowed"**

If you execute the same search using lowercase in the search value

**example.com/rdap-server/domains?nsLdhName=NS0.*.***

The server returns a list of results. 

The search should be case insensitive because the search value is a domain label.

**Comment by TheRedTrainer** [comment]
Verified. If the user execute a domain's search by nsLdhName using a value that includes only uppercase, the final validation is case insensitive, so it is possible to search a domain by nsLdhName regarding the use of uppercase/lowercase

**Comment by pcarana** [comment]
The issue was at an internal validation, the A-label that was created internally (always in lowercase) was compared against the original label of the request (uppercase, camelCase, BlaHblAhCase, ...). The solution was to compare this values ignoring case.
