### ISSUE TITLE
Allow wildcard in domains?nsIP search

### ISSUE THREAD

**Issue by TheRedTrainer** [NICMx/rdap-server#57]
Should rdap-server allow to search domains by nsIP using wildcards? According to RFC 7482...

> Searches for domain information by nameserver IP address are specified using this form:
> domains?nsIp=ZZZZ
> ZZZZ is a search pattern representing an IPv4 [RFC1166] or IPv6 [RFC5952] address.  The following URL would be used to search for domains that have been delegated to nameservers that resolve to the "192.0.2.0" address:
> https://example.com/rdap/domains?nsIp=192.0.2.0

It doesn't forbid the use of wildcards, neither recommend.

**Comment by pcarana** [comment]
The implementation is responsible of allow/block the use of wildcards when searching by IP. Whenever a partial search is made using an IP query parameter _(eg. domains?nsIp, nameservers?ip)_ the implementation will return an error code 422 with the description: **"Partial search using IPs isn't implemented, try another search"**.

Technically, now the server allows the use of wilcards but the implementation blocks it (is heavy work trying to interpret an IP partial search).

**Comment by TheRedTrainer** [comment]
Verified. The default implementation doesn't allow to use wildcards in partial searches using IP.
