### ISSUE TITLE
objectClassName’s property still appearing even when it’s value is “none”

### ISSUE THREAD

**Issue by ivonns** [NICMx/rdap-server#6]
The property “objectClassName” located in the properties files of domain, entities and namservers was set with “none” value. But when doing a query or search, the objectClassName is still appearing in the response. This value should not be appearing in the query/search since it has a “none” value.

**Comment by dhfelix** [comment]
The property can not be hidden, because it is required by the RFC to indicate the type of object being read.
It is removed from the privacy settings files to avoid confusion.
