### ISSUE TITLE
Improve error title for error code 422 ("Unprocessable Entity") in partial search

### ISSUE THREAD

**Issue by TheRedTrainer** [NICMx/rdap-server#60]
If the rdap server has the "allow_search_wildcars_anywhere" property (in configuration.properties) turned off and a client executes a partial search like 

http://localhost:8080/rdap-server/domains?nsLdhName=*test*

The following error message is displayed:

> {"rdapConformance":["rdap_level_0"],"errorCode":"422","title":"Unprocessable Entity","description":"Partial search can only have wildcards at the end of each label"}

However, this message could be confusing because the standard title for error code 422 mentions an "unprocessable entity", so it could be confused with the rdap entity object when a client is searching for a domain.

**Comment by pcarana** [comment]
The default title is now **"Unprocessable HTTP Entity"** to avoid confusion. The issue was at [NICMx/rdap-data-access-api](https://github.com/NICMx/rdap-data-access-api), still will be solved here.

**Comment by TheRedTrainer** [comment]
Reopen (bug). When a 422 error code is returned from server, the title keep showing the text "Unprocessable entity". 

{"rdapConformance":["rdap_level_0"],"errorCode":"422","title":"Unprocessable Entity","description":"Search pattern must be at least 5 characters, consecutive wildcards '*' are treated as only one character. Pattern received: *"}

This is probably caused because the DEFAULT_MSG in UnprocessableEntityException class (in the solution) is not used when the exception is created.

**Comment by pcarana** [comment]
Yep, the solution was incomplete. The title was set at `ExceptionResult`, the real fix was to update the title of the error at that class; please, try again.

**Comment by TheRedTrainer** [comment]
Verified. If an user perform a search that returns a 422 error code, the error message is displayed with the new title. For example

{"rdapConformance":["rdap_level_0"],"errorCode":"422","title":"Unprocessable HTTP Entity","description":"Partial search can only have one wildcard at each label"}
