### ISSUE TITLE
Internal server error (code 500) at /ip when using invalid cidr

### ISSUE THREAD

**Issue by pcarana** [NICMx/rdap-server#61]
If an invalid cidr is used when searching a valid IP, the server returns a **500** error code. Take this URL as an example to reproduce the issue: _/ip/1.2.3.4/a_

This is inconsistent with other responses, for instance: if the request _/ip/1.2.3.a_ is made the server will respond with a **400** error code.

The proposal is also to return the error code **400**.

Just to add more information of the internal error, this is a piece of my log:
```
sep 20, 2017 10:04:52 AM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [ip] in context with path [/rdap-server] threw exception
java.lang.NumberFormatException: For input string: "a"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
```

**Comment by TheRedTrainer** [comment]
This issue can be reproduced using a big decimal number (like 9999999999)

**Comment by pcarana** [comment]
Whenever an invalid value is sent as cidr (large number, text, etc.) the server will return a 400 error code with the description "Invalid cidr value".

**Comment by TheRedTrainer** [comment]
Verified. When an invalid value is sent as CIDR (text, special char, spaces, a double number, a large number, etc), the server returns the following error message:

{"rdapConformance":["rdap_level_0"],"errorCode":"400","description":"Invalid cidr value"}
