### ISSUE TITLE
domain and nameserver searches by ip's decimal equivalent

### ISSUE THREAD

**Issue by TheRedTrainer** [NICMx/rdap-server#63]
A client can search a domain or a nameserver by ip's decimal equivalent (for example, using '3823770255' instead of 227.234.26.143). However, this behaviour could be confusing (mainly while using wildcards like * ), wrong and not so frequently used. It doesn't even work properly with default implementation because if you search a nameserver by ip common format (227.234.26.143) the server returns a valid nameserver but if you search it using the decimal equivalent (3823770255) the server returns the following message:

"errorCode":"404","title":"Object not found","description":""

It is recommended to allow only domain and nameserver searches by ip using ipv4 and ipv6 standard format.

**Comment by pcarana** [comment]
A simple validation was added to avoid parsing decimals as IPs at: _"/domains?nsIp"_ and _"/nameservers?ip"_.

**Comment by TheRedTrainer** [comment]
Verified. When a user searches a domain or nameserver by ip using a wildcard, the following error message is returned:

{"rdapConformance":["rdap_level_0"],"errorCode":"422","title":"Unprocessable Entity","description":"Partial search using IPs isn't implemented, try another search"}
