### ISSUE TITLE
renderers.properties doesn't include a default configuration

### ISSUE THREAD

**Issue by TheRedTrainer** [NICMx/rdap-server#65]
The renderers.properties configuration file includes an empty default configuration. If the user doesn't define a renderer class, the server cannot start.

It's highly recommended to include a default configuration in order to help the new users to configure and test rdap-server more easily.

**Comment by dhfelix** [comment]
The properties file does not contain hidden default values, it is necessary for the user to configure at least one renderer.

To start the rdap-server server quickly, we decided to leave the reference implementation of the json-renderer and its corresponding configuration in the renderers.properties file. The user is free to remove the reference implementation and change the configuration of this properties file to use the renderer of his choice.

**Comment by TheRedTrainer** [comment]
Verified. The renderer properties file includes a default renderer with all the regarding configuration (class, main_mime, mimes) in order to start the server quickly with a reference renderer implementation.
