### ISSUE TITLE
'nameserver_as_domain_attribute' property isn't correctly validated

### ISSUE THREAD

**Issue by pcarana** [NICMx/rdap-server#68]
According to the property description at `configuration.properties`, its value must be a `boolean`, so if an invalid value is configured probably an error should be raised; but this isn't what happens.

Two things happen here:

- Whenever an invalid value is set, the property is loaded and stored as `false`. So, if the property has the value "potato" this will be treated as `false`.
- Whenever the property isn't set, only an INFO log is showed when starting the server with this message: __"Note: The key 'nameserver_as_domain_attribute' is not present in the data access configuration. Domain and Nameserver requests will be rejected"__.

If the property is expected to be a `boolean` then it should be validated as such.

Well, just to add something else, the INFO message mentioned earlier states that__"...'nameserver_as_domain_attribute' is not present in the data access configuration..."__ but the property is loaded at the general configuration of the server, so here's another inconsistency.

The suggestion is:

- Validate the property value, if it's a `boolean` then `true `and `false` are the only valid options (not null values, no "potato" values).
- Move the configuration property to the [implementation](https://github.com/NICMx/rdap-sql-provider) since there is where the property is needed and used.

**Comment by pcarana** [comment]
Both suggestions were implemented:

- The property value is validated as a `boolean`, if an invalid value is configured then the server will raise an exception to show the error.
- The property 'nameserver_as_domain_attribute' was moved to the file `data-access.properties` with a default value of `false`.

**Comment by pcarana** [comment]
The second suggestion:

> The property 'nameserver_as_domain_attribute' was moved to the file data-access.properties with a default value of false.

Wasn't adequate to the custom behavior of the configurations. The file where the default values must be, should be at the implementation, not at the server. The issue NICMx/rdap-sql-provider#11 was opened to attend this.

The first suggestion that was implemented:

> The property value is validated as a boolean, if an invalid value is configured then the server will raise an exception to show the error.

Is going to be at the provider, not at the server.

**Comment by pcarana** [comment]
The issue NICMx/rdap-sql-provider#11 has been solved, so now the default value of `nameserver_as_domain_attribute` is loaded from the implementation, not from the server's file `data-access.properties`.

**Comment by TheRedTrainer** [comment]
Verified. If the user configure the property "nameserver_as_domain_attribute" with a "true" value in "data-access.properties" file, the search for nameserver are not implemented on rdap-server. The default value is defined from implementation, and if the user deletes or comments the property in "data-access.properties" is loaded as "false" (the default value from implementation)
