### ISSUE TITLE
Links privacy attributes from main object's attributes (remarks, event, etc.) use the same configuration from their parent object

### ISSUE THREAD

**Issue by TheRedTrainer** [NICMx/rdap-server#69]
The user can configure the privacy for the attributes from the main objects (domain, nameserver, ip, autnum). These attributes include some of the following: handle, entities, status, lang, remarks, events, links, etc. In a similar way, some of these attributes (remarks, events, links) have attributes which privacy settings could be configured too (for example: lang, description, title, links(again), etc). 

However, there is a third level of attributes: the attributes of attributes of attributes of an object (for example, the attributes from link attribute from remark attribute from domain object). In this case, the user cannot configure these last attributes privacy settings because the rdap server assume the configuration for the attribute with the same name in the parent level (for example, using the privacy settings for links attributes from domain object instead of requiring a specific setting for links attributes from remark attributes from domain object). This assumption is invalid because the user may want to hide the links from a domain object and display the links for the remarks from a domain, and not only to hide every link in all the hierarchies.  

The list of all the attributes that requires a way to configure their own privacy:
- domain.events.links
- domain.remarks.links
- domain.secureDNS.dsData.events
- domain.secureDNS.dsData.events.links
- domain.secureDNS.dsData.links
- domain.secureDNS.keyData.events.
- domain.secureDNS.keyData.events.links
- domain.secureDNS.keyData.links
- nameserver.events.links
- nameserver.remarks.links
- ipnetworks.events.links
- ipnetworks.remarks.links
- autnum.events.links
- autnum.remarks.links

**Comment by dhfelix** [comment]
The missing configuration was added to the latest commit in devl-it07 branch

**Comment by TheRedTrainer** [comment]
Verified. Every privacy configuration file allows to define the privacy for every attribute and object, including the deepest levels such as object's event links.
