### ISSUE TITLE
Mistaken error code for a zone which is not being managed

### ISSUE THREAD

**Issue by ivonns** [NICMx/rdap-server#7]
Description
It has been made a query for a domain name which has a zone that is not being managed. The error code resulting for that request was “400”. However, the error code should be “404” because the request does not contain a malformed query, it’s just that the server doesn’t have the information being requested neither the knowledge of where the information can be found. This situation only happens when doing a query. (In the case of the search the code error appears correctly)

**Comment by DAlpuche** [comment]
Changed the exception thrown when requesting a unmanaged zone, from 400 to 404. When the user request a domain with a non-managed zone, the server will respond with the following message:
"The RDAP server doesn't have information about the requested zone"
