### ISSUE TITLE
shiro.ini default configuration is missing

### ISSUE THREAD

**Issue by TheRedTrainer** [NICMx/rdap-server#71]
If an user tries to run rdap-server for the first time, a severe error happens and the following stack trace is displayed at localhost log:

> 31-Oct-2017 11:38:05.387 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.listenerStart Exception sending context initialized event to listener instance of class org.apache.shiro.web.env.EnvironmentLoaderListener
>  java.lang.IllegalArgumentException: Line argument must contain a key and a value.  Only one string token was found.
> 	at org.apache.shiro.config.Ini$Section.splitKeyValue(Ini.java:601)
> 	at org.apache.shiro.config.Ini$Section.toMapProps(Ini.java:626)
> 	at org.apache.shiro.config.Ini$Section.<init>(Ini.java:523)
> 	at org.apache.shiro.config.Ini$Section.<init>(Ini.java:504)
> 	at org.apache.shiro.config.Ini.addSection(Ini.java:361)
> 	at org.apache.shiro.config.Ini.load(Ini.java:393)
> 	at org.apache.shiro.config.Ini.load(Ini.java:295)
> 	at org.apache.shiro.config.Ini.load(Ini.java:283)
> 	at org.apache.shiro.web.env.IniWebEnvironment.convertPathToIni(IniWebEnvironment.java:355)
> 	at org.apache.shiro.web.env.IniWebEnvironment.createIni(IniWebEnvironment.java:244)
> 	at org.apache.shiro.web.env.IniWebEnvironment.getDefaultIni(IniWebEnvironment.java:215)
> 	at org.apache.shiro.web.env.IniWebEnvironment.parseConfig(IniWebEnvironment.java:101)
> 	at org.apache.shiro.web.env.IniWebEnvironment.init(IniWebEnvironment.java:69)
> 	at org.apache.shiro.util.LifecycleUtils.init(LifecycleUtils.java:45)
> 	at org.apache.shiro.util.LifecycleUtils.init(LifecycleUtils.java:40)
> 	at org.apache.shiro.web.env.EnvironmentLoader.createEnvironment(EnvironmentLoader.java:313)
> 	at org.apache.shiro.web.env.EnvironmentLoader.initEnvironment(EnvironmentLoader.java:139)
> 	at org.apache.shiro.web.env.EnvironmentLoaderListener.contextInitialized(EnvironmentLoaderListener.java:58)
> 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4853)
> 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5314)
> 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
> 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:753)
> 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:729)
> 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
> 	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:976)
> 	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1853)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> 

Maybe the exception is caused by the following missing shiro default configuration:
ds.driverClassName =
ds.url =
ds.username =
ds.password =
customRealm.authenticationQuery =
customRealm.userRolesQuery = 

It is necessary to provide to the user all the minimal configuration required to run the server.

**Comment by pcarana** [comment]
Now Shiro uses the filter 'anon' and disables authentication by default, to avoid this kind of configuration issues. If the implementer wishes to enable the filter, then several lines should be uncommented (the docs will state this).

**Comment by TheRedTrainer** [comment]
Verified. The default configuration for shiro.ini file is to use the anon filter in order to allow a new user to run rdap-server without further user/authentication configuration. If an user wants to configure all the credentials management, almost all the properties include a default usable value (except for data source url, username and password).
