### ISSUE TITLE
Should we keep regex searches code in rdap-server?

### ISSUE THREAD

**Issue by TheRedTrainer** [NICMx/rdap-server#76]
Currently, the code that allows to execute searches using regex as it is defined in "Registration Data Access Protocol (RDAP) Search Using POSIX Regular Expressions" draft ( https://tools.ietf.org/html/draft-fregly-regext-rdap-search-regex-00.html ) is included in rdap-server; however, as far as I know, this functionality is neither mentioned nor supported  in rdap documentation. The code could work but it wasn't tested. 

Should rdap-server keep this code (keeping also the development and testing efforts) and provide support? Or should we remove all the code and functionality?

**Comment by pcarana** [comment]
Well, the code is there but definitely out of date. The implementation is based on [version 1](https://tools.ietf.org/html/draft-fregly-regext-rdap-search-regex-01) of the draft; today the draft is at [version 3](https://tools.ietf.org/html/draft-fregly-regext-rdap-search-regex-03). Version 2 had some major changes that the server doesn't have.

The reason why this has been implemented even before the draft became a RFC, is that the draft had potential to achieve the goal of becoming a RFC.

> Should rdap-server keep this code (keeping also the development and testing efforts) and provide support? Or should we remove all the code and functionality?

This depends on the draft's evolution, for now the server will keep it (it's a hidden gem that can be valued in the future). The documentation will stay the same.

**Comment by pcarana** [comment]
Just to avoid problems, a new configuration flag has been added: `allow_regex_searches`. This will enable/disable the use of regex searches that the server currently supports; the behavior is disabled by default.
