### ISSUE TITLE
Missing notices when the information can’t be displayed

### ISSUE THREAD

**Issue by ivonns** [NICMx/rdap-server#8]
By doing a query and the information of one of the nodes can’t be displayed, it shows an empty bracket. Instead of the brackets, it should appear a notice with a description about the reason the information cannot being shown.

**Comment by DAlpuche** [comment]
Added Notices and remarks for privacy as defined in RFC 7483:
Added Notices when the resultSet was truncated, and remarks when the object was affected by the privacy setting defined by the user.
