### ISSUE TITLE
Broken Link in documentation

### ISSUE THREAD

**Issue by huwsteadCL** [NICMx/rdap-server#82]
Looking to setup Red Dog using Red Dog's built in schema (Option 3 - Using Red Dog’s builtin schema)

Specifically I am reviewing:
https://www.reddog.mx/migration.html

This provides a link to a script to generate the DB at:
https://raw.githubusercontent.com/NICMx/rdap-sql-provider/master/src/main/resources/META-INF/sql/Database.sql

That results in a 404..  Can you advise on the correct location / update documentation

**Comment by pcarana** [comment]
Thanks for the report, we're working on it. The link has moved to https://raw.githubusercontent.com/NICMx/rdap-sql-provider/master/src/test/resources/META-INF/sql/Database.sql (from the directory "main" to "test").

**Comment by pcarana** [comment]
The link error has been fixed at 1a5d301ecaf59bcf485e6aef2cc9febf22139256.

Please refresh the page at https://www.reddog.mx/migration.html and check the fixed links.
