### ISSUE TITLE
Remarks vs Notices

### ISSUE THREAD

**Issue by huwsteadCL** [NICMx/rdap-server#83]
Within the RDAP Response Profile (v2.1) there are two references to _notices_ rather than _remarks_

These are covered in Sections 2.6.3 and 2.11.  Given that I can't find a table that covers notices can you advise how one would meant this requirement?  (at the moment I am using remarks which seems to not be the correct thing to do)

Thanks
Huw

**Comment by dhfelix** [comment]
This requirement is covered in the latest available version of RDAP (1.3.0).

In the following [link](https://www.reddog.mx/notices.html), you can find the documentation to add the structure of the notices.

Please let me know if this covers your needs or if something is wrong.

**Comment by huwsteadCL** [comment]
perfect.  use of domain.xml is fully satisfying this requirement
