### ISSUE TITLE
Section 2.7.6 - Last Update of RDAP Database

### ISSUE THREAD

**Issue by huwsteadCL** [NICMx/rdap-server#85]
Would it be possible to relax DB restrictions on entity_events such that eve_id isn't required to be unique?

I was hoping to add a single "last update of the RDAP database" event and tie all domains / contacts to it rather than creating one per domain and contact.

At the moment the DB restrictions prevent this.

**Comment by dhfelix** [comment]
From what I am reading, I am assuming that you are using our reference database (a.k.a. RDAP-sql-provider).

This requirement was covered in RDAP-server version [1.3.0](https://www.reddog.mx/home/2018/09/19/server-1.3.0.html), [here](https://www.reddog.mx/events.html) I can leave you the link of the documentation for you requirement, and then tell me if it is enough to cover your needs.

Do not hesitate to ask us if you have questions in the documentation, you can also give us some feedback.

In addition, we are working to try to comply with the gTLD RDAP profile february-2019

**Comment by huwsteadCL** [comment]
Thanks very much for the feedback.  Currently checking out the events.xml route and seems like it will provide a good solution here.  That said, at present we can't get the events to show in RDAP responses 

Beyond adding events.xml in the correct location (and with the correct format) is there anything further that for need doing?

P..S.
Also noticed a couple of things in your example events.xml content on https://www.reddog.mx/events.html

1.  The example have am opening <events> tag but the corresponding closing tag is </notices> rather than </events>

2.  https://www.reddog.mx/events.html states "A required eventAction a string denoting the reason for the event. (Only valid eventActions are allowed, lower case, you can see which are the valid ones here)".   The here link however shows the eventAction as including uppercase characters i.e. "last update of RDAP database".  The example of the page is then showing the lowercase variant of that string i.e.
 <eventAction>last update of rdap database</eventAction>

**Comment by dhfelix** [comment]
hmm, could you check what the Logs say ?, as it is an optional file, the log is in INFO level.
It's something like:
```
INFO: Optional File 'events.xml' not found, continue.
...
```
Also I think that in that same info log, it is mention the path where the RDAP-server looks for the events.xml file.
Finally, just to mention, this feature is available in RDAP-server version 1.3.0.


> The example have am opening tag but the corresponding closing tag is rather than

you are right , thanks , copy-paste quirks :P 

> The example of the page is then showing the lowercase variant of that string i.e.
last update of rdap database.

hmmm, I see, the eventAction in the xml file needs to be in lower case for our application, but when it shows up as a rdap-response, it is shown as specified by the IANA website

**Comment by huwsteadCL** [comment]
Perfect - Thanks very much.. We were being dumb and somehow had an older version than 1.3.0.  All good now
