### ISSUE TITLE
Standardize bad request responses

### ISSUE THREAD

**Issue by TheRedTrainer** [NICMx/rdap-server#87]
When an user executes a query that retrieves a http 400 response, the corresponding message is not standardized. For example, the following queries provides the corresponding messages:

http://localhost:8080/rdap-server/domains?name=xn--1caPÓTÁTÓPÁTÁTÁ.com
```
{
"rdapConformance": [
"rdap_level_0"
],
"errorCode": "400",
"description": [
"Bad Request"
]
}
```

http://localhost:8080/rdap-server/domain/xn--1caPÓTÁTÓPÁTÁTÁ.com
```
{
"rdapConformance": [
"rdap_level_0"
],
"errorCode": "400",
"description": [
"Bad Request: Invalid domain label: 'xn--1caPÓTÁTÓPÁTÁTÁ.com'"
]
}
```

http://localhost:8080/rdap-server/nameservers?ip=blahblah
```
{
"rdapConformance": [
"rdap_level_0"
],
"errorCode": "400",
"description": [
"Invalid IP address"
]
}
```

**Comment by dhfelix** [comment]
The first result, is the generic response, no message was found.
The second response has a redundant word "Bad Request" because errorCode 400 means bad request. 

We decided to remove the redundant word "Bad Request" in error responses that have a message.

**Comment by TheRedTrainer** [comment]
Verified. The redundant text "Bad request" was removed
