### ISSUE TITLE
rdapConformance configurated is not displaying unicode chars

### ISSUE THREAD

**Issue by TheRedTrainer** [NICMx/rdap-server#88]
If a custom rdapConformance including some unicode chars (for example "测试" or "тэст"),  is configured in configuration.properties, the rdap json response cannot display the unicode chars properly, showing only chars like "¿¿¿" instead of the configured rdapConformance.

`{"rdapConformance":["rdap_level_0","lunar_nic_conformance","¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿","¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿¿"],"objectClassName":"nameserver"`

UPDATE:
The ""¿¿¿¿" chars were displayed due an issue with the configuration.properties encoding. However, the rdapConformance is not displaying the correct chars yet:

configuration.properties: 

`add_custom_conformance = lunar_nic_conformance, тэсттэсuт , 测试测试测试测试`

rdap-server response:

```
{
 "rdapConformance": [
   "rdap_level_0",
   "lunar_nic_conformance",
   "ÑÑÑÑÑÑÑuÑ",
   "æµè¯æµè¯æµè¯æµè¯",
```

**Comment by dhfelix** [comment]
Apparently this is a known issue in properties for Java 8 and previous versions, the properties file must be enconded as ISO-8859-1.
Your custom conformance should looks like 

`add_custom_conformance = lunar_nic_conformance, \u0442\u044D\u0441\u0442\u0442\u044D\u0441u\u0442 , \u6D4B\u8BD5\u6D4B\u8BD5\u6D4B\u8BD5\u6D4B\u8BD5`

if you want to see the next result:

```json
   "rdapConformance": [
        "rdap_level_0",
        "lunar_nic_conformance",
        "тэсттэсuт",
        "测试测试测试测试"
    ],
```

source: https://softwarei18n.org/using-unicode-in-java-resource-bundles-6220776b6099

**Comment by TheRedTrainer** [comment]
Verified. If the user configureS the rdapConformance using the escaped chars as mentioned by @dhfelix , the rdapConformance are displayed correctly on rdap queries.
