### ISSUE TITLE
TLD (domain zone) is case sensitive

### ISSUE THREAD

**Issue by TheRedTrainer** [NICMx/rdap-server#90]
If an user tries to query a domain but the TLD/domain zone is given in caps, the rdap server return the following response:

```
...
errorCode: 400,
description: [Invalid domain label: 'domain.orG'] 
...
```

despite the fact that 'domain.org' is a valid domain in rdap server's database

**Comment by dhfelix** [comment]
This issue happen when the flag "allow_labels_mixture" is set to false and an error in code.
The issue is solved in rdap-core

**Comment by TheRedTrainer** [comment]
Verified. If the user queries a domain changing the TLD case, the server ignores these changes and retrieves the domain anyway.
