### ISSUE TITLE
"last update of RDAP database" event is not created for nameservers/domains/entities searches when is_db_data_live is true

### ISSUE THREAD

**Issue by TheRedTrainer** [NICMx/rdap-server#93]
When an user configures the "is_db_data_live" property as true, and there are no events configured (in the events.xml file or database) for a domain/entity/nameserver, and a client executes a multiple nameservers/domains/entities search, the event is not created and added to every nameserver/domain/entity retrieved by the search.

**Comment by dhfelix** [comment]
I replicate this issue, it seems some code problem, while in lookup path servlets works as expected, in search path servlets doesn’t work when the events of the objects are empty.

Meanwhile you can workaround this by creating an event of type “last update of rdap database” in the file “events.xml” and set the flag “is_db_data_live” as true.

**Comment by TheRedTrainer** [comment]
Verified. This issue has been fixed
