### ISSUE TITLE
rdapConformance - Default Value

### ISSUE THREAD

**Issue by huwsteadCL** [NICMx/rdap-server#97]
Within Section 1.3 of the RDAP Response Profile it states:

"For clarity, conformance to the current document MUST be noted with a value of "icann_rdap_response_profile_0""

The default for RedDog responses seems to be "rdap_level_0".   Shouldn't this be changed to "icann_rdap_response_profile_0"?

OR is it a case that I should add "add_custom_conformance" within configuration.properties (which I then believe would show both "rdap_level_0" and "icann_rdap_response_profile_0")

**Comment by dhfelix** [comment]
From RFC 7483 Section 4.1

> The data structure named "rdapConformance" is an array of strings,
>    each providing a hint as to the specifications used in the
>    construction of the response.

rdap_level_0 means that the response is conformance with the RFC7483.
If you want to add more conformances, you add it in the "add_custom_conformance" property configuration.

So, you second thought is correct.

**Comment by huwsteadCL** [comment]
Thanks for the super quick response.  You guys are awesome!
(and apologies in advance I may have a few more questions for you)
